version: 2.3.7
files:
  - url: >-
      https://github.com/manoranjan-5562/kultworks-updates/releases/download/v2.3.7/KultWorks-Setup-2.3.7-dev.exe
    sha512: >-
      S09XvgCAQthDclvIwPyUPPX7Wxnsspg7m1C422PALJTJI1eOnraRXCWBEGwT2iEdSXl7qvlAWDjVJ4zB41+MRA==
    size: 105279297
path: >-
  https://github.com/manoranjan-5562/kultworks-updates/releases/download/v2.3.7/KultWorks-Setup-2.3.7-dev.exe
sha512: >-
  S09XvgCAQthDclvIwPyUPPX7Wxnsspg7m1C422PALJTJI1eOnraRXCWBEGwT2iEdSXl7qvlAWDjVJ4zB41+MRA==
releaseDate: '2026-06-03T16:22:42.712Z'
